compress_assets: off
gzip_assets: off

javascripts:
  assets:
    - dependencies/jquery-1.7.2.min.js
    - dependencies/underscore-min.js
    - dependencies/backbone-min.js
    - dependencies/backbone-associations-min.js
    - dependencies/bootstrap-min.js
    - models/*.js
    - controllers/*.js
    - views/*.js
    - backbone/app.js